# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.srcs/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/xdma_bram_xdma_0_0.xci
# IP: The module: 'xdma_bram_xdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_0/xdma_bram_xdma_0_0_pcie3_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_bram_xdma_0_0_pcie3_ip || ORIG_REF_NAME==xdma_bram_xdma_0_0_pcie3_ip} -quiet] -quiet

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_1/xdma_v4_1_26_blk_mem_64_reg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_26_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_26_blk_mem_64_reg_be} -quiet] -quiet

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_2/xdma_v4_1_26_blk_mem_64_noreg_be.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_26_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_26_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_0/source/xdma_bram_xdma_0_0_pcie3_ip-PCIE_X0Y1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_bram_xdma_0_0_pcie3_ip || ORIG_REF_NAME==xdma_bram_xdma_0_0_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_0/synth/xdma_bram_xdma_0_0_pcie3_ip_ooc.xdc

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_1/xdma_v4_1_26_blk_mem_64_reg_be_ooc.xdc

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_2/xdma_v4_1_26_blk_mem_64_noreg_be_ooc.xdc

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/xdma_bram_xdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bram_xdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/source/xdma_bram_xdma_0_0_pcie3_7vx_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bram_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/synth/xdma_bram_xdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bram_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.srcs/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/xdma_bram_xdma_0_0.xci
# IP: The module: 'xdma_bram_xdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_0/xdma_bram_xdma_0_0_pcie3_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_bram_xdma_0_0_pcie3_ip || ORIG_REF_NAME==xdma_bram_xdma_0_0_pcie3_ip} -quiet] -quiet

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_1/xdma_v4_1_26_blk_mem_64_reg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_26_blk_mem_64_reg_be || ORIG_REF_NAME==xdma_v4_1_26_blk_mem_64_reg_be} -quiet] -quiet

# IP: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_2/xdma_v4_1_26_blk_mem_64_noreg_be.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xdma_v4_1_26_blk_mem_64_noreg_be || ORIG_REF_NAME==xdma_v4_1_26_blk_mem_64_noreg_be} -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_0/source/xdma_bram_xdma_0_0_pcie3_ip-PCIE_X0Y1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==xdma_bram_xdma_0_0_pcie3_ip || ORIG_REF_NAME==xdma_bram_xdma_0_0_pcie3_ip} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_0/synth/xdma_bram_xdma_0_0_pcie3_ip_ooc.xdc

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_1/xdma_v4_1_26_blk_mem_64_reg_be_ooc.xdc

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/ip_2/xdma_v4_1_26_blk_mem_64_noreg_be_ooc.xdc

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/xdma_bram_xdma_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bram_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/source/xdma_bram_xdma_0_0_pcie3_7vx_ip.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bram_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/PCie/fpga_pcie_x1_xdma_bram_blockdesign/pcie_xdma_test.gen/sources_1/bd/xdma_bram/ip/xdma_bram_xdma_0_0/synth/xdma_bram_xdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'xdma_bram_xdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
