set_property SRC_FILE_INFO {cfile:c:/Vulcan/Protocol/Display/dp_pt/dp_pt.gen/sources_1/ip/v_dp_rxss1_0/bd_0/ip/ip_0/bd_ac35_0_dp_0.xdc rfile:../../../dp_pt.gen/sources_1/ip/v_dp_rxss1_0/bd_0/ip/ip_0/bd_ac35_0_dp_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Vulcan/Protocol/Display/dp_pt/dp_pt.gen/sources_1/ip/v_dp_rxss1_0/bd_0/ip/ip_0/bd_ac35_0_dp_0_clocks.xdc rfile:../../../dp_pt.gen/sources_1/ip/v_dp_rxss1_0/bd_0/ip/ip_0/bd_ac35_0_dp_0_clocks.xdc id:2 order:LATE scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:3 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:4 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:5 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:6 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:7 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:8 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:9 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:10 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:11 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:12 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:13 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:14 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:15 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:16 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:17 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:18 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:19 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:20 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:21 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:22 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:23 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:24 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:25 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:26 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:27 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:28 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:29 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:30 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:31 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:32 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:33 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_gray.tcl id:34 order:LATE scoped_inst:{inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst} unmanaged:yes} [current_design]
set_property SRC_FILE_INFO {cfile:C:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl rfile:../../../../../../../Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/tcl/xpm_memory_xdc.tcl id:35 order:LATE scoped_inst:inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_aux_inst/displayport_v8_1_7_rx_dpcd_inst/gen_vendor_specific.inst unmanaged:yes} [current_design]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_interrupt_inst/i_mode_change_interrupt_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*CE} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_interrupt_inst/FSM_onehot_i_mode_change_interrupt_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_framing*_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/i_*_match_event_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-4 -description "sampling is controlled by FSM. Values will be updated per frame basis. Safe to ignore" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_framing*_inst/cfg_rx_vidmode_regs_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/i_updated_timing_parameters_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "i_fifo_reset CDC-11 fix" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_main_inst/i_fifo_reset_reg*}]] -to   *PIN
set_property src_info {type:SCOPED_XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "Even though a flop has been kept before the synchronizer in each of the LANE instantiations, the tool is optimizing is taking only one flop in lane-2 and giving fanout to other lane's sync cells by optimizing the flops in other lanes. Hence waiving off. This signal is used to reset few things inside 8b10b fifo logic when training is started. Since the pattern match is a cyclic process, it is safe even if the pattern is missed the first time because of this fanout on this signal. Hence safe to waiveoff." -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *i_training_in_progress_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync_cell_lt_in_prog_dec_clk_inst*}]]
set_property src_info {type:SCOPED_XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-1 -description "This corresponds to Async RAM read which is allowed for RAM64 cell as per its PG" -from [get_pins -quiet -filter {REF_PIN_NAME=~*CLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *vcpayload_active_buffer_buffer_inst/gen_multi_port_ram64m*}]] -to   *PIN
set_property src_info {type:SCOPED_XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "VBID bit which remains constant atleast for a given video horizontal line time" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/cfg_rx_vidmode_regs_reg[148]*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync_cell_audio_mute_str*_inst/syncstages_ff_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "VBID bit which remains constant atleast for a given video horizontal line time" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_user_dtg_inst/cfg_rx_vidmode_regs_reg[148]*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync_cell_vbid*inst/syncstages_ff_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "Adaptive sync MSA signals which remain constant atleast for a video frame time" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_framing*_inst/as_msa_vfp_vld_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync_cell_rx_as_vfp_str*_inst/syncstages_ff_reg*}]]
set_property src_info {type:SCOPED_XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -scope -internal -quiet -user displayport_rx -tags 10897 -type CDC -id CDC-11 -description "Adaptive sync MSA signals which remain constant atleast for a video frame time" -from [get_pins -quiet -filter {REF_PIN_NAME=~*C} -of_objects [get_cells -hierarchical -filter {NAME =~ *rx_framing*_inst/as_msa_vfp_vld_reg*}]] -to   [get_pins -quiet -filter {REF_PIN_NAME=~*D} -of_objects [get_cells -hierarchical -filter {NAME =~ *sync_cell_as_msa/syncstages_ff_reg*}]]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 10.000 -from [get_pins -of [get_cells -hierarchical -filter {NAME =~*/cfg_rx_vidmode_regs_reg*}] -filter {REF_PIN_NAME == C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~*/apb_rdata_reg*}] -filter {REF_PIN_NAME == D}]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 10.000 -from [get_pins -of [get_cells -hierarchical -filter {NAME =~*/syncstages_ff_reg*}] -filter {REF_PIN_NAME == C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~*/apb_rdata_reg*}] -filter {REF_PIN_NAME == D}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 10.000 -from [get_pins -of [get_cells -hierarchical -filter {NAME =~*/matched_r_20b_reg*}] -filter {REF_PIN_NAME == C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~*/apb_dpcd_read_data_reg*}] -filter {REF_PIN_NAME == D}]
set_property src_info {type:SCOPED_XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_max_delay -datapath_only 10.000 -from [get_pins -of [get_cells -hierarchical -filter {NAME =~*/matched_r_20b_reg*}] -filter {REF_PIN_NAME == C}] -to [get_pins -of [get_cells -hierarchical -filter {NAME =~*/apb_rdata_reg*}] -filter {REF_PIN_NAME == D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:3 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:4 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:5 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:6 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:7 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:8 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:9 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst
set_property src_info {type:SCOPED_XDC file:10 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:11 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:12 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:13 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:14 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:15 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:16 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:17 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_inst}
set_property src_info {type:SCOPED_XDC file:18 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:19 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:20 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:21 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:22 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:23 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:24 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:25 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.wr_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:26 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/displayport_v8_1_7_rx_lane0_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:27 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_1.displayport_v8_1_7_rx_lane1_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:28 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane2_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:29 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_lane_gr_than_2.displayport_v8_1_7_rx_lane3_inst/gen_dp13_connections.dut_rx_8b10b_data/displayport_v8_1_7_rx_8b10b_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst
set_property src_info {type:SCOPED_XDC file:30 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_0/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:31 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_1/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:32 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_2/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:33 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance {inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_main_inst/gen_user_modules[0].displayport_v8_1_7_rx_user_inst/displayport_v8_1_7_rx_user_fifo_lane_3/displayport_v8_1_7_rx_vid_fifo_inst/fifo_gen_inst/gnuram_async_fifo.xpm_fifo_base_inst/gen_cdc_pntr.rd_pntr_cdc_dc_inst}
set_property src_info {type:SCOPED_XDC file:34 line:23 export:INPUT save:NONE read:READ} [current_design]
create_waiver -internal -scoped -type CDC -id {CDC-6} -user "xpm_cdc" -tags "1009444" -desc "The CDC-6 warning is waived as it is safe in the context of XPM_CDC_GRAY." -from [get_pins -quiet {src_gray_ff_reg*/C}] -to [get_pins -quiet {dest_graysync_ff_reg*/D}]
current_instance
current_instance inst/core_top_inst/dport_link_inst/displayport_v8_1_7_rx_link_inst/displayport_v8_1_7_rx_aux_inst/displayport_v8_1_7_rx_dpcd_inst/gen_vendor_specific.inst
set_property src_info {type:SCOPED_XDC file:35 line:55 export:INPUT save:NONE read:READ} [current_design]
set my_var [get_property dram_emb_xdc [get_cells -quiet -hier -filter {PRIMITIVE_SUBGROUP==LUTRAM || PRIMITIVE_SUBGROUP==dram || PRIMITIVE_SUBGROUP==uram || PRIMITIVE_SUBGROUP==BRAM}]]
