-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dpss_vck190_pt_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    img_dout : IN STD_LOGIC_VECTOR (119 downto 0);
    img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    img_empty_n : IN STD_LOGIC;
    img_read : OUT STD_LOGIC;
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (119 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (14 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (14 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    Height_val : IN STD_LOGIC_VECTOR (12 downto 0);
    WidthOut_val : IN STD_LOGIC_VECTOR (12 downto 0);
    colorFormat_val_dout : IN STD_LOGIC_VECTOR (1 downto 0);
    colorFormat_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val_empty_n : IN STD_LOGIC;
    colorFormat_val_read : OUT STD_LOGIC );
end;


architecture behav of dpss_vck190_pt_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal colorFormat_val_blk_n : STD_LOGIC;
    signal colorFormat_val_read_reg_518 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_block_state1 : BOOLEAN;
    signal sub_ln343_fu_271_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal sub_ln343_reg_524 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_280_ap_return : STD_LOGIC_VECTOR (12 downto 0);
    signal rows_reg_529 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal div_cast1_fu_364_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal div_cast1_reg_570 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    signal sub_fu_378_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal sub_reg_575 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal icmp_ln348_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln348_reg_580 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal and_ln348_fu_407_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln348_reg_588 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out1_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out2_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out3 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out3_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out4 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out4_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out5 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out5_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out6 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out6_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out7 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out7_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out8 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out8_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out9 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out9_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out10 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out10_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out11 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out11_ap_vld : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_idle : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_ready : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_img_read : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TREADY : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TDATA : STD_LOGIC_VECTOR (119 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TVALID : STD_LOGIC;
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TKEEP : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TSTRB : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_reg_unsigned_short_s_fu_280_ap_ce : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_reg_unsigned_short_s_fu_286_ap_return : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_reg_unsigned_short_s_fu_286_ap_ce : STD_LOGIC;
    signal sof_reg_172 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start_reg : STD_LOGIC := '0';
    signal p_loc_fu_150 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc15_fu_146 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc16_fu_142 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc17_fu_138 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc18_fu_134 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc19_fu_130 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc20_fu_126 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc21_fu_122 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc22_fu_118 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc23_fu_114 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc24_fu_110 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal p_loc25_fu_106 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln348_1_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_102 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal i_2_fu_396_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_fu_260_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_fu_253_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln343_fu_267_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal div_cast_fu_374_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dpss_vck190_pt_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sub_ln343 : IN STD_LOGIC_VECTOR (5 downto 0);
        p_out : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out_ap_vld : OUT STD_LOGIC;
        p_out1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out1_ap_vld : OUT STD_LOGIC;
        p_out2 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out2_ap_vld : OUT STD_LOGIC;
        p_out3 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out3_ap_vld : OUT STD_LOGIC;
        p_out4 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out4_ap_vld : OUT STD_LOGIC;
        p_out5 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out5_ap_vld : OUT STD_LOGIC;
        p_out6 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out6_ap_vld : OUT STD_LOGIC;
        p_out7 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out7_ap_vld : OUT STD_LOGIC;
        p_out8 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out8_ap_vld : OUT STD_LOGIC;
        p_out9 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out9_ap_vld : OUT STD_LOGIC;
        p_out10 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out10_ap_vld : OUT STD_LOGIC;
        p_out11 : OUT STD_LOGIC_VECTOR (3 downto 0);
        p_out11_ap_vld : OUT STD_LOGIC );
    end component;


    component dpss_vck190_pt_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_dout : IN STD_LOGIC_VECTOR (119 downto 0);
        img_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        img_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        img_empty_n : IN STD_LOGIC;
        img_read : OUT STD_LOGIC;
        m_axis_video_TREADY : IN STD_LOGIC;
        sof : IN STD_LOGIC_VECTOR (0 downto 0);
        div_cast1 : IN STD_LOGIC_VECTOR (10 downto 0);
        sub : IN STD_LOGIC_VECTOR (11 downto 0);
        empty_62 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_63 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_64 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_65 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_66 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_67 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_68 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_69 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_70 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_71 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty_72 : IN STD_LOGIC_VECTOR (3 downto 0);
        empty : IN STD_LOGIC_VECTOR (3 downto 0);
        m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (119 downto 0);
        m_axis_video_TVALID : OUT STD_LOGIC;
        m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (14 downto 0);
        m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (14 downto 0);
        m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component dpss_vck190_pt_v_frmbuf_rd_0_0_reg_unsigned_short_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        d : IN STD_LOGIC_VECTOR (12 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (12 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184 : component dpss_vck190_pt_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start,
        ap_done => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done,
        ap_idle => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_idle,
        ap_ready => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_ready,
        sub_ln343 => sub_ln343_reg_524,
        p_out => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out,
        p_out_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out_ap_vld,
        p_out1 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out1,
        p_out1_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out1_ap_vld,
        p_out2 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out2,
        p_out2_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out2_ap_vld,
        p_out3 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out3,
        p_out3_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out3_ap_vld,
        p_out4 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out4,
        p_out4_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out4_ap_vld,
        p_out5 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out5,
        p_out5_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out5_ap_vld,
        p_out6 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out6,
        p_out6_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out6_ap_vld,
        p_out7 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out7,
        p_out7_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out7_ap_vld,
        p_out8 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out8,
        p_out8_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out8_ap_vld,
        p_out9 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out9,
        p_out9_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out9_ap_vld,
        p_out10 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out10,
        p_out10_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out10_ap_vld,
        p_out11 => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out11,
        p_out11_ap_vld => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out11_ap_vld);

    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203 : component dpss_vck190_pt_v_frmbuf_rd_0_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start,
        ap_done => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done,
        ap_idle => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_idle,
        ap_ready => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_ready,
        img_dout => img_dout,
        img_num_data_valid => ap_const_lv3_0,
        img_fifo_cap => ap_const_lv3_0,
        img_empty_n => img_empty_n,
        img_read => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_img_read,
        m_axis_video_TREADY => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TREADY,
        sof => sof_reg_172,
        div_cast1 => div_cast1_reg_570,
        sub => sub_reg_575,
        empty_62 => p_loc25_fu_106,
        empty_63 => p_loc24_fu_110,
        empty_64 => p_loc23_fu_114,
        empty_65 => p_loc22_fu_118,
        empty_66 => p_loc21_fu_122,
        empty_67 => p_loc20_fu_126,
        empty_68 => p_loc19_fu_130,
        empty_69 => p_loc18_fu_134,
        empty_70 => p_loc17_fu_138,
        empty_71 => p_loc16_fu_142,
        empty_72 => p_loc15_fu_146,
        empty => p_loc_fu_150,
        m_axis_video_TDATA => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TDATA,
        m_axis_video_TVALID => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TVALID,
        m_axis_video_TKEEP => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TKEEP,
        m_axis_video_TSTRB => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TSTRB,
        m_axis_video_TUSER => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TUSER,
        m_axis_video_TLAST => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TLAST,
        m_axis_video_TID => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TID,
        m_axis_video_TDEST => grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TDEST);

    grp_reg_unsigned_short_s_fu_280 : component dpss_vck190_pt_v_frmbuf_rd_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        d => Height_val,
        ap_return => grp_reg_unsigned_short_s_fu_280_ap_return,
        ap_ce => grp_reg_unsigned_short_s_fu_280_ap_ce);

    grp_reg_unsigned_short_s_fu_286 : component dpss_vck190_pt_v_frmbuf_rd_0_0_reg_unsigned_short_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        d => WidthOut_val,
        ap_return => grp_reg_unsigned_short_s_fu_286_ap_return,
        ap_ce => grp_reg_unsigned_short_s_fu_286_ap_ce);





    and_ln348_reg_588_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                and_ln348_reg_588 <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    and_ln348_reg_588 <= and_ln348_fu_407_p2;
                end if; 
            end if;
        end if;
    end process;


    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln348_1_fu_402_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    colorFormat_val_read_reg_518_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                colorFormat_val_read_reg_518 <= ap_const_lv2_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    colorFormat_val_read_reg_518 <= colorFormat_val_dout;
                end if; 
            end if;
        end if;
    end process;


    div_cast1_reg_570_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                div_cast1_reg_570 <= ap_const_lv11_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    div_cast1_reg_570 <= grp_reg_unsigned_short_s_fu_286_ap_return(12 downto 2);
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln348_1_fu_402_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_ready = ap_const_logic_1)) then 
                    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_1_fu_102_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                i_1_fu_102 <= ap_const_lv13_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    i_1_fu_102 <= ap_const_lv13_0;
                elsif (((icmp_ln348_1_fu_402_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                    i_1_fu_102 <= i_2_fu_396_p2;
                end if; 
            end if;
        end if;
    end process;


    icmp_ln348_reg_580_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                icmp_ln348_reg_580 <= ap_const_lv1_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    icmp_ln348_reg_580 <= icmp_ln348_fu_384_p2;
                end if; 
            end if;
        end if;
    end process;


    p_loc15_fu_146_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc15_fu_146 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out1_ap_vld = ap_const_logic_1))) then 
                    p_loc15_fu_146 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out1;
                end if; 
            end if;
        end if;
    end process;


    p_loc16_fu_142_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc16_fu_142 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out2_ap_vld = ap_const_logic_1))) then 
                    p_loc16_fu_142 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out2;
                end if; 
            end if;
        end if;
    end process;


    p_loc17_fu_138_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc17_fu_138 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out3_ap_vld = ap_const_logic_1))) then 
                    p_loc17_fu_138 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out3;
                end if; 
            end if;
        end if;
    end process;


    p_loc18_fu_134_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc18_fu_134 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out4_ap_vld = ap_const_logic_1))) then 
                    p_loc18_fu_134 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out4;
                end if; 
            end if;
        end if;
    end process;


    p_loc19_fu_130_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc19_fu_130 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out5_ap_vld = ap_const_logic_1))) then 
                    p_loc19_fu_130 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out5;
                end if; 
            end if;
        end if;
    end process;


    p_loc20_fu_126_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc20_fu_126 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out6_ap_vld = ap_const_logic_1))) then 
                    p_loc20_fu_126 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out6;
                end if; 
            end if;
        end if;
    end process;


    p_loc21_fu_122_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc21_fu_122 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out7_ap_vld = ap_const_logic_1))) then 
                    p_loc21_fu_122 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out7;
                end if; 
            end if;
        end if;
    end process;


    p_loc22_fu_118_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc22_fu_118 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out8_ap_vld = ap_const_logic_1))) then 
                    p_loc22_fu_118 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out8;
                end if; 
            end if;
        end if;
    end process;


    p_loc23_fu_114_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc23_fu_114 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out9_ap_vld = ap_const_logic_1))) then 
                    p_loc23_fu_114 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out9;
                end if; 
            end if;
        end if;
    end process;


    p_loc24_fu_110_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc24_fu_110 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out10_ap_vld = ap_const_logic_1))) then 
                    p_loc24_fu_110 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out10;
                end if; 
            end if;
        end if;
    end process;


    p_loc25_fu_106_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc25_fu_106 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out11_ap_vld = ap_const_logic_1))) then 
                    p_loc25_fu_106 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out11;
                end if; 
            end if;
        end if;
    end process;


    p_loc_fu_150_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                p_loc_fu_150 <= ap_const_lv4_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out_ap_vld = ap_const_logic_1))) then 
                    p_loc_fu_150 <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_p_out;
                end if; 
            end if;
        end if;
    end process;


    rows_reg_529_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                rows_reg_529 <= ap_const_lv13_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    rows_reg_529 <= grp_reg_unsigned_short_s_fu_280_ap_return;
                end if; 
            end if;
        end if;
    end process;


    sof_reg_172_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sof_reg_172 <= ap_const_lv1_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done = ap_const_logic_1))) then 
                    sof_reg_172 <= and_ln348_reg_588;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    sof_reg_172 <= ap_const_lv1_1;
                end if; 
            end if;
        end if;
    end process;


    sub_ln343_reg_524_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sub_ln343_reg_524(2) <= '0';
                sub_ln343_reg_524(3) <= '0';
                sub_ln343_reg_524(4) <= '0';
                sub_ln343_reg_524(5) <= '0';
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                                        sub_ln343_reg_524(5 downto 2) <= sub_ln343_fu_271_p2(5 downto 2);
                end if; 
            end if;
        end if;
    end process;


    sub_reg_575_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                sub_reg_575 <= ap_const_lv12_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    sub_reg_575 <= sub_fu_378_p2;
                end if; 
            end if;
        end if;
    end process;

    sub_ln343_reg_524(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state5, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state6, icmp_ln348_1_fu_402_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln348_1_fu_402_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    and_ln348_fu_407_p2 <= (sof_reg_172 and icmp_ln348_reg_580);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done)
    begin
        if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done)
    begin
        if ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, colorFormat_val_empty_n)
    begin
                ap_block_state1 <= ((colorFormat_val_empty_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state5, icmp_ln348_1_fu_402_p2)
    begin
        if (((icmp_ln348_1_fu_402_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5, icmp_ln348_1_fu_402_p2)
    begin
        if (((icmp_ln348_1_fu_402_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    colorFormat_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val_blk_n <= colorFormat_val_empty_n;
        else 
            colorFormat_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    colorFormat_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val_read <= ap_const_logic_1;
        else 
            colorFormat_val_read <= ap_const_logic_0;
        end if; 
    end process;

    div_cast1_fu_364_p4 <= grp_reg_unsigned_short_s_fu_286_ap_return(12 downto 2);
    div_cast_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div_cast1_fu_364_p4),12));
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_start_reg;
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_ap_start_reg;
    grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TREADY <= (m_axis_video_TREADY and ap_CS_fsm_state6);

    grp_reg_unsigned_short_s_fu_280_ap_ce_assign_proc : process(ap_CS_fsm_state4, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            grp_reg_unsigned_short_s_fu_280_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_280_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_reg_unsigned_short_s_fu_286_ap_ce_assign_proc : process(ap_CS_fsm_state4, grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_341_1_fu_184_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            grp_reg_unsigned_short_s_fu_286_ap_ce <= ap_const_logic_1;
        else 
            grp_reg_unsigned_short_s_fu_286_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_396_p2 <= std_logic_vector(unsigned(i_1_fu_102) + unsigned(ap_const_lv13_1));
    icmp_ln348_1_fu_402_p2 <= "1" when (i_1_fu_102 = rows_reg_529) else "0";
    icmp_ln348_fu_384_p2 <= "1" when (div_cast1_fu_364_p4 = ap_const_lv11_0) else "0";

    img_read_assign_proc : process(grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_img_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            img_read <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_img_read;
        else 
            img_read <= ap_const_logic_0;
        end if; 
    end process;

    m_axis_video_TDATA <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TDATA;
    m_axis_video_TDEST <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TDEST;
    m_axis_video_TID <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TID;
    m_axis_video_TKEEP <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TKEEP;
    m_axis_video_TLAST <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TLAST;
    m_axis_video_TSTRB <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TSTRB;
    m_axis_video_TUSER <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TUSER;
    m_axis_video_TVALID <= grp_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_350_3_fu_203_m_axis_video_TVALID;
    sub_fu_378_p2 <= std_logic_vector(unsigned(div_cast_fu_374_p1) + unsigned(ap_const_lv12_FFF));
    sub_ln343_fu_271_p2 <= std_logic_vector(unsigned(tmp_fu_253_p3) - unsigned(zext_ln343_fu_267_p1));
    tmp_fu_253_p3 <= (colorFormat_val_read_reg_518 & ap_const_lv4_0);
    tmp_s_fu_260_p3 <= (colorFormat_val_read_reg_518 & ap_const_lv2_0);
    zext_ln343_fu_267_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_260_p3),6));
end behav;
