# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Protocol/HDMI/HDMI_img/HDMI_img.srcs/sources_1/ip/rom_ip/rom_ip.xci
# IP: The module: 'rom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Protocol/HDMI/HDMI_img/HDMI_img.gen/sources_1/ip/rom_ip/rom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Vulcan/Protocol/HDMI/HDMI_img/HDMI_img.srcs/sources_1/ip/rom_ip/rom_ip.xci
# IP: The module: 'rom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Protocol/HDMI/HDMI_img/HDMI_img.gen/sources_1/ip/rom_ip/rom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
