# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/ip_0/bd_98fb_dp_0_rs_decoder_v9_0_20_viv.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_98fb_dp_0_rs_decoder_v9_0_20_viv || ORIG_REF_NAME==bd_98fb_dp_0_rs_decoder_v9_0_20_viv} -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_98fb_dp_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_98fb_dp_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_98fb_dp_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_98fb_dp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_98fb_dp_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_98fb_dp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/ip_0/bd_98fb_dp_0_rs_decoder_v9_0_20_viv.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_98fb_dp_0_rs_decoder_v9_0_20_viv || ORIG_REF_NAME==bd_98fb_dp_0_rs_decoder_v9_0_20_viv} -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_98fb_dp_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_98fb_dp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_98fb_dp_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_98fb_dp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_v_dp_rxss1_0_0/bd_0/ip/ip_0/bd_98fb_dp_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_98fb_dp_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
