# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0.xci
# IP: The module: 'dpss_vck190_pt_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/bd_3191.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191 || ORIG_REF_NAME==bd_3191} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_0/bd_3191_S00_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S00_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_1/bd_3191_const_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_const_0_0 || ORIG_REF_NAME==bd_3191_const_0_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_2/bd_3191_S01_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S01_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_3/bd_3191_S02_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S02_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_4/bd_3191_S03_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S03_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_5/bd_3191_S04_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S04_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_6/bd_3191_S05_AXI_nmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S05_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_7/bd_3191_MC0_ddrc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_MC0_ddrc_0 || ORIG_REF_NAME==bd_3191_MC0_ddrc_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_7/ip_0/bd_3191_MC0_ddrc_0_phy.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_3191_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_3191_S00_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S00_AXI_nmu_0} -quiet] {/bd_3191_S00_AXI_nmu_0_top_INST } ]/bd_3191_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_3191_S01_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S01_AXI_nmu_0} -quiet] {/bd_3191_S01_AXI_nmu_0_top_INST } ]/bd_3191_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_3191_S02_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S02_AXI_nmu_0} -quiet] {/bd_3191_S02_AXI_nmu_0_top_INST } ]/bd_3191_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_3191_S03_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S03_AXI_nmu_0} -quiet] {/bd_3191_S03_AXI_nmu_0_top_INST } ]/bd_3191_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_3191_S04_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S04_AXI_nmu_0} -quiet] {/bd_3191_S04_AXI_nmu_0_top_INST } ]/bd_3191_S04_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_3191_S05_AXI_nmu_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S05_AXI_nmu_0} -quiet] {/bd_3191_S05_AXI_nmu_0_top_INST } ]/bd_3191_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_7/hdl/par/bd_3191_MC0_ddrc_0_ip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_MC0_ddrc_0 || ORIG_REF_NAME==bd_3191_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0.xci
# IP: The module: 'dpss_vck190_pt_axi_noc_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/bd_3191.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191 || ORIG_REF_NAME==bd_3191} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_0/bd_3191_S00_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S00_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_1/bd_3191_const_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_const_0_0 || ORIG_REF_NAME==bd_3191_const_0_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_2/bd_3191_S01_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S01_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_3/bd_3191_S02_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S02_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_4/bd_3191_S03_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S03_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_5/bd_3191_S04_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S04_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_6/bd_3191_S05_AXI_nmu_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S05_AXI_nmu_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_7/bd_3191_MC0_ddrc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_MC0_ddrc_0 || ORIG_REF_NAME==bd_3191_MC0_ddrc_0} -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_7/ip_0/bd_3191_MC0_ddrc_0_phy.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_3191_MC0_ddrc_0_phy || ORIG_REF_NAME==bd_3191_MC0_ddrc_0_phy} -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_0/xdc/bd_3191_S00_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S00_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S00_AXI_nmu_0} -quiet] {/bd_3191_S00_AXI_nmu_0_top_INST } ]/bd_3191_S00_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_2/xdc/bd_3191_S01_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S01_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S01_AXI_nmu_0} -quiet] {/bd_3191_S01_AXI_nmu_0_top_INST } ]/bd_3191_S01_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_3/xdc/bd_3191_S02_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S02_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S02_AXI_nmu_0} -quiet] {/bd_3191_S02_AXI_nmu_0_top_INST } ]/bd_3191_S02_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_4/xdc/bd_3191_S03_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S03_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S03_AXI_nmu_0} -quiet] {/bd_3191_S03_AXI_nmu_0_top_INST } ]/bd_3191_S03_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_5/xdc/bd_3191_S04_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S04_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S04_AXI_nmu_0} -quiet] {/bd_3191_S04_AXI_nmu_0_top_INST } ]/bd_3191_S04_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_6/xdc/bd_3191_S05_AXI_nmu_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_S05_AXI_nmu_0 || ORIG_REF_NAME==bd_3191_S05_AXI_nmu_0} -quiet] {/bd_3191_S05_AXI_nmu_0_top_INST } ]/bd_3191_S05_AXI_nmu_0_top_INST ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/bd_0/ip/ip_7/hdl/par/bd_3191_MC0_ddrc_0_ip.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_3191_MC0_ddrc_0 || ORIG_REF_NAME==bd_3191_MC0_ddrc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_axi_noc_0_0/dpss_vck190_pt_axi_noc_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_axi_noc_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
