# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_oddr_0_0/dpss_vck190_pt_oddr_0_0.xci
# IP: The module: 'dpss_vck190_pt_oddr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_oddr_0_0/dpss_vck190_pt_oddr_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_oddr_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.srcs/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_oddr_0_0/dpss_vck190_pt_oddr_0_0.xci
# IP: The module: 'dpss_vck190_pt_oddr_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Vulcan/Protocol/Display/v_dp_rxss1_0_ex/v_dp_rxss1_0_ex.gen/sources_1/bd/dpss_vck190_pt/ip/dpss_vck190_pt_oddr_0_0/dpss_vck190_pt_oddr_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpss_vck190_pt_oddr_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
